### PR TITLE
fix `bower install angular-sockjs`

### PR DESCRIPTION
**Pull request by pr80ik**

### CODE REVIEW

**Comment by pr80ik** [comment]
Note that a tag v0.1.0 is also required for bower to work correctly.

current workaround is to use the command: `bower install -S git@github.com:pr80ik/angular-sockjs.git#0.1.0`

**Comment by bendrucker** [comment]
Awesome, thanks! I'll do a 0.1.0 tag on the same commit

**Comment by bendrucker** [comment]
Did my best to clean up the tags. Haven't used Bower in a long time, apologies for breaking things.

**Comment by pr80ik** [comment]
Its working as expected now. I'm glad I could help.

**Pull request closed without merging**
